openapi: 3.0.1

info:
  title: will be replaced
  description: This information will be replaced by the SpringFox config information
  version: 0.0.1

paths:
  /videocalls/new:
    post:
      tags:
        - video-controller
      summary: 'Create a new video call room Id [Authorization: Role: consultant]'
      operationId: createVideoCall
      parameters:
        - name: RCUserId
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/CreateVideoCallDTO'
        required: true
      responses:
        201:
          description: CREATED - video call room Id was successfully created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/CreateVideoCallResponseDTO'
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        403:
          description: 'FORBIDDEN - no/invalid role/authorization, CSRF token or consultant without
          permission for given session'
        404:
          description: NOT FOUND - Session not found
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
      security:
        - Bearer: [ ]

  /videocalls/stop/{roomId}:
    post:
      tags:
        - video-controller
      summary: 'Stops a video call [Auth: consultant]'
      description: 'This is basically for stats.'
      operationId: stopVideoCall
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: NO CONTENT
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        403:
          description: FORBIDDEN - no/invalid CSRF token
        404:
          description: NOT FOUND - room ID unknown
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition

  /videocalls/reject:
    post:
      tags:
        - video-controller
      summary: 'Reject a video call [Authorization: Role: user]'
      operationId: rejectVideoCall
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/RejectVideoCallDTO'
        required: true
      responses:
        200:
          description: OK - video call was successfully rejected
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        403:
          description: FORBIDDEN - no/invalid CSRF token
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
      security:
        - Bearer: [ ]

  /videocalls/{roomId}/jwt:
    get:
      tags:
        - video-controller
      summary: 'Gets the moderatorToken (for consultants) or the invitationToken (for others) 
        [Authorization: Role: consultant, anonymous]'
      operationId: getWebToken
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK - web token returned
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/VideoCallInfoDTO'
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        403:
          description: FORBIDDEN - no/invalid CSRF token
        404:
          description: NOT FOUND - rcGroupId unknown
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
  /videocalls/room/{jitsiRoomId}:
    post:
      tags:
        - video-controller
      summary: 'Creates a new room [Authorization: Role: jitsi-technical]'
      operationId: createRoom
      parameters:
        - name: jitsiRoomId
          in: path
          required: true
          schema:
            type: long
      responses:
        200:
          description: OK - successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoRoomResponseDTO'
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition


components:
  schemas:
    CreateVideoCallDTO:
      type: object
      required:
        - sessionId
      properties:
        sessionId:
          type: integer
          format: int64
        initiatorDisplayName:
          type: string
    CreateVideoCallResponseDTO:
      type: object
      required:
        - moderatorVideoCallUrl
      properties:
        moderatorVideoCallUrl:
          type: string
          example: https://video.call/332a573d-7c74-4080-8353-7954eca066f9?jwt={moderatorToken}
          description: Moderator video call URL containing moderator role and guest join link
    RejectVideoCallDTO:
      type: object
      required:
        - rcGroupId
        - initiatorRcUserId
        - initiatorUsername
      properties:
        rcGroupId:
          type: string
          example: "tb89h3tjkerg967"
        initiatorRcUserId:
          type: string
          example: "ag89h3tjkerg94t"
        initiatorUsername:
          type: string
          example: "consultant23"
    VideoCallInfoDTO:
      type: object
      required:
        - domain
        - jwt
      properties:
        domain:
          type: string
        jwt:
          type: string

    VideoRoomResponseDTO:
      type: object
      properties:
        jitsiRoomId:
          type: long
          example: 12132
        videoLink:
          type: string
          example: 12132
        createDate:
          type: string
        updateDate:
          type: string

  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
